### ISSUE TITLE
JSS templates are missing from the web database

### ISSUE THREAD

**Issue by sussexrick** [Sitecore/docker-images#237] opened 2020-02-07 12:57 UTC
Using the following images:

* `sitecore-xm-jss-sqldev:9.2.0-windowsservercore-ltsc2019`
* `sitecore-xm-solr:9.2.0-nanoserver-1809`
* `sitecore-xm-jss-cm:9.2.0-windowsservercore-ltsc2019`

The databases are seeded from clean copies on startup, but the `/sitecore/templates/Foundation/JavaScript Services` item and its descendants are only present in `master`. They should be published to `web` too.

Unless you publish these items manually JSS apps fail on CD with a "Layout not found" error in the browser and the following in the logs:

```
1248 18:05:16 ERROR Data template '{061CBA15-5474-4B91-8A06-17903B102B82}' not found for item '/sitecore/content/jss-react-sample-app' in 'web' database
 720 18:05:37 ERROR Data template '{35C61E90-47DD-43DD-83A8-D1C4D5119720}' not found for item '/sitecore/layout/Layouts/Project/jss-react-sample-app/jss-react-sample-app Layout' in 'web' database
```

**Comment by sussexrick** [comment] 2020-02-07 16:28
If I run "publish site" it says 89 items are published from `master` to `web`.

**Comment by pbering** [comment] 2020-02-08 12:00
Hi there, you should always to a publish just as if you installed a module manually. We can only do what the current WDP's does, and they don't have DACPAC's for the web database, only core/master. While building the CM images it is not started and there is no SQL server running, so doing a publish is not possible either.

Therefore I will close this issue as the current behavior is "by design".

**Closed by pbering** 2020-02-08 12:00 UTC
Labels: wontfix
