### ISSUE TITLE
Documentation: sitecore-tags.md anchors do not work

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/docker-images#427] opened 2020-11-06 14:48 UTC
In here [https://github.com/Sitecore/docker-images/blob/master/tags/sitecore-tags.md](https://github.com/Sitecore/docker-images/blob/master/tags/sitecore-tags.md) some of the anchor links do not work and maybe should be adjusted.
Specifically, the anchors that have a / in the name do not work and should be adjusted.

**Comment by jeanfrancoislarente** [comment] 2020-11-27 12:05
I've reported this internally @sebastiantecsi. I've put a note as to what needs to change, it's a minor change but because the MD is created via an automated script, it does require some magical changes to be made.

Thanks for reporting. I'll close this issue once the product team applies the fix internally.

**Comment by jeanfrancoislarente** [comment] 2020-11-30 13:49
Fixed by product team on Friday. Just confirmed. Thanks!

**Closed by jeanfrancoislarente** 2020-11-30 13:49 UTC
Labels: bug, sitecore
