### ISSUE TITLE
Sitecore Publishing Module missing

### ISSUE THREAD

**Issue by gthvidsten** [Sitecore/docker-images#334] opened 2020-07-06 15:21 UTC
# ISSUE

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior
`.\Build.ps1` finishes succesfully

## Actual behavior

`.\Build.ps1` can't download the "Sitecore Publishing Module"

## Additional information

The following warnings are displayed in the output from `.\Build.ps1`:

```
WARNING: 16:58:53:408: Required package 'Sitecore Publishing Module 9.3.0.0 rev. r00546.2197.scwdp.zip' not available for download because the url property is empty, please copy 'Sitecore
Publishing Module 9.3.0.0 rev. r00546.2197.scwdp.zip' into 'C:\Projects\3rdParty\SitecoreDockerImages\packages' manually.
```

```
WARNING: 17:05:59:087: Optional source file 'C:\Projects\3rdParty\SitecoreDockerImages\packages\Sitecore Publishing Module 9.3.0.0 rev. r00546.2197.scwdp.zip' is missing...
```

I guess this is due to the fact that `/sitecore-packages.json` has the following settings for the Publishing Module:

```
  "Sitecore Publishing Module 9.3.0.0 rev. r00546.2197.scwdp.zip": {
    "url": "",
    "hash": ""
  }
```

I guess the URL should be: `https://dev.sitecore.net/~/media/417C43AC4F334C4085D18925367FE79A.ashx`
which downloads a file called: `Sitecore Publishing Module 9.3.0.0 rev. r00546.2197.zip` (does not match the filename listed in the warning).
I don't know what should be the hash for this.

- Output from `docker info`:
```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 6
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.900)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.93GiB
 Name: ITUMX-GTH
 ID: OC66:XLNL:V4AC:TYWC:OZQZ:7EBI:AMEL:RX77:Y5NJ:SLHB:LGHK:U74N
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2020-07-06T16:20:50.1758845+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Are you running inside a virtualized Windows machine or physical:
Physical

## Steps to reproduce the behavior

  1. Clone this repository
  2. Execute `.\Build.ps1` and observe the warnings described above

**Comment by sshushliapin** [comment] 2020-07-07 06:56
Duplicate of #262? Unfortunately it got stuck for some reason....

**Closed** 2020-10-21 18:55 UTC
