### ISSUE TITLE
Unable to build images for ltsc2019 due to timeout errors

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/docker-images#189] opened 2019-12-26 09:33 UTC
I do not recall when this became a problem but now I'm almost unable to build images for ltsc2019. I receive numerous timeout errors  
- on different build steps 
- for different sitecore versions and 
- on different build agents

There are some of the errors:

```
### Processing 'sitecore-xp-cd:9.3.0-windowsservercore-ltsc2019'...
...
Step 10/19 : RUN Copy-Item -Path 'C:\\inetpub\\wwwroot\\App_Config\\Include\\Examples\\Sitecore.Owin.Authentication.IdentityServer.Disabler.config.example' -Destination 'C:\\inetpub\\wwwroot\\App_Config\\Include\\Sitecore.Owin.Authentication.IdentityServer.Disabler.config';     Copy-Item -Path 'C:\\inetpub\\wwwroot\\App_Config\\Include\\Examples\\Sitecore.LoadBalancing.config.example' -Destination 'C:\\inetpub\\wwwroot\\App_Config\\Include\\Sitecore.LoadBalancing.config';     New-Item -Path 'C:\\inetpub\\wwwroot\\upload' -ItemType Directory | Out-Null;     New-Item -Path 'C:\\inetpub\\wwwroot\\sitecore\\shell\\override' -ItemType Directory | Out-Null;     Remove-Item -Path 'C:\\inetpub\\wwwroot\\App_Data\\logs' -Force -Recurse;
 ---> Running in 9d3d87a2a92d
##[error]docker : container 9d3d87a2a92d7d1592cf153160581c21ace84d24a10f45e14201da8317bc1ab3 encountered an error during Start: 
##[error]failure in a Windows system call: The operation timed out because a response was not received from the virtual machine 
```

```
### Processing 'sitecore-xp-xconnect:9.3.0-windowsservercore-ltsc2019'...
...
Step 12/17 : RUN $xdts = [System.Collections.ArrayList]@();     $xdts.AddRange(@(Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\*.xdt'));     $xdts.AddRange(@(Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\App_Config\\*.xdt' -Recurse));     $xdts.AddRange(@(Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\App_Data\\*.xdt' -Recurse));     $xdts | ForEach-Object { & 'C:\\inetpub\\wwwroot\\temp\\install\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path $_.FullName.Replace('.xdt', '') -XdtPath $_.FullName -XdtDllPath 'C:\\inetpub\\wwwroot\\temp\\install\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };     $xdts | ForEach-Object { Remove-Item -Path $_.FullName; };
 ---> Running in 0ff70f6d8a01
container 0ff70f6d8a0140837f4e6388038d8593dab9e949a47cd8494ef1f77db6286196 encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the virtual machine or container. (0xc0370109)
Failed: docker image build --isolation 'hyperv' --build-arg BASE_IMAGE=mcr.microsoft.com/dotnet/framework/aspnet:4.8-wi
ndowsservercore-ltsc2019 --build-arg ASSETS_IMAGE=sitecore-assets:9.3.0-nanoserver-1809 --build-arg ASSETS_USE_WDP='C:\
packages\Sitecore 9.3.0 (OnPrem)_xp0xconnect.scwdp.zip' --tag 'sitecore-xp-xconnect:9.3.0-windowsservercore-ltsc2019' '
```

```
### Processing 'sitecore-xm-cd:9.0.2-windowsservercore-ltsc2019'...
...
Step 10/20 : RUN New-Item -Path 'C:\\inetpub\\wwwroot\\upload' -ItemType Directory | Out-Null;     New-Item -Path 'C:\\inetpub\\wwwroot\\sitecore\\shell\\override' -ItemType Directory | Out-Null;     Remove-Item -Path 'C:\\inetpub\\wwwroot\\App_Data\\logs' -Force -Recurse;
 ---> Running in b7263cec9283
container b7263cec9283456f85ce3347bd9dd471b76d106a90a2cecc249a1e54ce369b0d encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the virtual machine or container. (0xc0370109)
Failed: docker image build --isolation 'hyperv' --build-arg BASE_IMAGE=mcr.microsoft.com/dotnet/framework/aspnet:4.8-wi
ndowsservercore-ltsc2019 --build-arg ASSETS_IMAGE=sitecore-assets:9.0.2-nanoserver-1809 --build-arg ASSETS_USE_WDP='C:\
packages\XM\Sitecore 9.0.2 rev. 180604 (OnPrem)_cd.scwdp.zip' --build-arg SC_ROLE_CONFIG_DIRECTORY=.\config\cd --build-
arg SC_ROLE_DEFINE='ContentDelivery' --tag 'sitecore-xm-cd:9.0.2-windowsservercore-ltsc2019' 'C:\vsts\agent04\_work\4\s
\windows\9.0.2\sitecore-xm'
```

I've got ltsc2019, 1903 and 1909 build machines. All of them are compatible with ltsc2019 and all of them have this timeout problem. I did not notice any lack of resources. In the same time there are no issues with 1903 and 1909 images. They are just always green...

Any idea why is that?

**Comment by pbering** [comment] 2019-12-30 11:10
Hi, unfortunately this is something we have been seeing lately, seems to have started to happen late November and I suspect some Windows Update have introduced this since there has not been any Docker engine updates.

I haven't noticed that is only happens on ltsc2019 when testing and trying to reproduce. I have run many test on Windows 10 physical machines and well at latest Windows Server 2019 (ltsc, 1909, 1903) VM images on Azure on different machine types (F4,8,32 and D4,8,32). It seems to not make any differences which size, CPU or memory.

Also tried different approaches to mitigate the issue that actual seem to work but it's not something I like to commit into master.

1. Right after running `docker image build` in the PowerShell Module you can run `docker image prune --force` which takes about ~3 seconds every time it runs. It works and actually seems to be faster when building everything, but since dangling images are pruned then there is not much cached when running builds again.
1. Same place as above but instead of prune then do a `Start-Sleep -Seconds 3` will also work and builds after are faster.

Based on above it seems that the Docker engine needs to somehow "cool down" in between each build O_O

Found some old dead issues on various Docker repos with the same error message `encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the virtual machine or container. (0xc0370109)` but none had any usable information.

I think we need to make a new issue somewhere and gather debug logs...

**Comment by sshushliapin** [comment] 2020-01-03 10:43
Ok, thanks. Closing this one.

**Comment by pbering** [comment] 2020-01-03 13:45
Just updated one of my agents (Windows 10) with latest Docker CE and Windows updates and a full prine and now the timeout error is gone but now I randomly get `encountered an error during Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)`, I just retry the job a few times and then it completes :(

Have you seen that error or do you still get the timeout errors?

**Comment by sshushliapin** [comment] 2020-01-06 06:11
I installed all the updates on my 2019 server. I've got 2 successful builds and two builds failed with old timeout error... So it's a bit better now but not fully solved.

I haven't seen the Windows system call error so far.

**Comment by pbering** [comment] 2020-01-12 10:30
In my quest for getting debug logs for this so I and create a issue, I tested adding `"shutdown-timeout": 60` to the daemon.json Docker config and it seems to fix the issue some how. I now have 5 successful in a row (all tags and full prune in between).

Please try to add that config to your machines and see it helps as it did here.

**Comment by sshushliapin** [comment] 2020-01-20 10:10
Nope... still fails... I tried set experimental mode but that did not help either:

```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true,
  "shutdown-timeout": 60
}
```

**Comment by pbering** [comment] 2020-01-20 10:12
did you restart the docker service so the config is reloaded, before you tried again?

**Comment by sshushliapin** [comment] 2020-01-20 10:20
Of course. Even rebooted the entire machine...

**Comment by pbering** [comment] 2020-01-20 10:25
well that should do it :) ... can you try to set debug to false and verify that it's also false in `docker info` under "Debug Mode"? This is to verify that you are making changes to the correct daemon.json config file...

**Comment by sshushliapin** [comment] 2020-01-27 07:33
>  can you try to set debug to false and verify that it's also false in docker info under "Debug Mode"?

Yep. The settings change is applied.
I guess, in general, it works but sometimes I still can see timeout errors...

![image](https://user-images.githubusercontent.com/4719165/73156841-c2520680-40e7-11ea-8872-92c952a7681b.png)

I assume the rare errors are not critical and the issue can be closed.

**Comment by pbering** [comment] 2020-01-27 07:57
Thanks for the feedback and I will close this for now.

**Closed by pbering** 2020-01-27 07:57 UTC

**Comment by gravypower** [comment] 2020-02-20 01:47
Also run into this, it could also be cause by this issue:

https://support.microsoft.com/en-au/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

I ensured that my docker host was upto date and all build fine. I also added the "shutdown-timeout": 60 as suggested above.

**Comment by anarsen** [comment] 2020-02-21 08:10
This might be related to #249
