### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by briankgarland** [Sitecore/docker-images#229] opened 2020-01-30 02:14 UTC
Any idea why this failed?

![image](https://user-images.githubusercontent.com/9375476/73414200-503a1700-42cb-11ea-850c-093f4f0cebf5.png)

**Comment by briankgarland** [comment] 2020-01-30 02:30
![image](https://user-images.githubusercontent.com/9375476/73414997-c9d30480-42cd-11ea-9081-54e893a343ce.png)

**Comment by pbering** [comment] 2020-01-30 08:08
Hi there! Are you sure that Docker _is_ running? You can verify with `docker system info`.

**Comment by daniel-simpson-alinta** [comment] 2020-02-12 21:21
I'm also getting this issue:
* I've set up an Azure DevOps build agent on my local machine (as a stopgap until I have "proper" CI tooling in place)
* Building the Sitecore Images directly via `.\Build.ps1` works well
* Building via Azure DevOps (on the same machine, but via the agent) via `.\Build.ps1` is having the same issue described above

Looks like this is caused by The Azure DevOps agent not having access to read docker system info, similar to [this StackOverflow answer](https://stackoverflow.com/questions/51190889/setting-up-docker-permission-to-vsts-agent-in-a-private-pipeline#answer-51208533).

Will give this a go and report back.

**Comment by daniel-simpson** [comment] 2020-02-12 21:22
I'm also getting this issue:
* I've set up an Azure DevOps build agent on my local machine (as a stopgap until I have "proper" CI tooling in place)
* Building the Sitecore Images directly via `.\Build.ps1` works well
* Building via Azure DevOps (on the same machine, but via the agent) via `.\Build.ps1` is having the same issue described above

Looks like this is caused by The Azure DevOps agent not having access to read docker system info, similar to [this StackOverflow answer](https://stackoverflow.com/questions/51190889/setting-up-docker-permission-to-vsts-agent-in-a-private-pipeline#answer-51208533).

Will give this a go and report back.

**Comment by daniel-simpson** [comment] 2020-02-12 21:37
Yep, the piece of JSON the script is trying to parse contains the answer:

```json
{
  "ServerErrors": [
    "error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/info: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running."
  ],
  "ClientInfo": {
    "Debug": false,
    "Plugins": [],
    "Warnings": null
  }
}
```

Is it difficult to bail out of the script at this point if there are server errors?  Or is this just down to setting up your client (/build agent) effectively?

**Comment by pbering** [comment] 2020-02-13 07:57
Hi Daniel, yes this is a permission issue. The vsts agent should run either as SYSTEM (ie. parsing `-runAsService --windowsLogonAccount "NT AUTHORITY\SYSTEM"` when configuring) or the account that it runs as should be a member of the local group "docker-users" on Windows 10 or "administrators" on Windows Server 2019.

**Comment by pbering** [comment] 2020-02-17 12:58
Did it work and can we close this issue?

**Comment by daniel-simpson-alinta** [comment] 2020-02-17 21:23
My Windows Server 2019 build is no longer having this issue after the above steps, thank you for the help.

@briankgarland have you tried the above?

**Comment by briankgarland** [comment] 2020-02-17 22:58
Not yet but I will as soon as possible. Thanks.

**Comment by pbering** [comment] 2020-03-19 14:19
Closing this for now :)

**Closed by pbering** 2020-03-19 14:19 UTC
