### ISSUE TITLE
Build is not running due to index size issue

### ISSUE THREAD

**Issue by skalai1** [Sitecore/docker-images#238] opened 2020-02-07 14:26 UTC
Write-InlineProgress : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

We are getting this error on build.ps

**Comment by michaellwest** [comment] 2020-02-07 15:06
Did this error occur locally in the console, ISE, or perhaps Azure DevOps?

**Comment by hermanussen** [comment] 2020-02-07 15:18
I'm seeing this same behaviour. Here's my log in Azure DevOps.

```
2020-02-07T14:43:24.8652914Z 14:43:24:857: Downloading 'https://dev.sitecore.net/~/media/D1F694E4238C438B8464FC1ABFF06C87.ashx' to 'Z:\dockerassets\Sitecore 9.3.0 rev. 003498 (WDP XM1 packages).zip'...
2020-02-07T14:43:33.7450738Z ##[error]Write-InlineProgress : Index was out of range. Must be non-negative and less than the size of the collection.
2020-02-07T14:43:33.7499533Z ##[error]Parameter name: index
At E:\redactedpath\modules\SitecoreImageBuilder\1.0.0\Private\Invoke-FileDownloa

2020-02-07T14:43:33.7592459Z ##[error]d.ps1:285 char:17

2020-02-07T14:43:33.7685632Z ##[error]+ ...             Write-InlineProgress -Activity "Downloading" -PercentComp ...

2020-02-07T14:43:33.7775607Z ##[error]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2020-02-07T14:43:33.7863755Z ##[error]    + CategoryInfo          : OperationStopped: (:) [Write-InlineProgress], ArgumentOutOfRangeException

2020-02-07T14:43:33.7948855Z ##[error]    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Write-InlineProgress

2020-02-07T14:43:33.8030879Z ##[error] 

2020-02-07T14:43:33.8121415Z ##[error]PowerShell exited with code '1'.
```

**Comment by hermanussen** [comment] 2020-02-07 15:23
After downloading the required packages and uploading them to the file share manually, this is skipped (obviously because the script doesn't need to do this anymore). This might explain why the issue gets overlooked; if you already have the packages, then this code is no longer touched.

**Comment by michaellwest** [comment] 2020-02-07 16:20
I figured out the issue. Such a silly thing to discover.

This line was causing an issue beccause $Error did not have any errors. I added some error checking. 
```powershell
if ($Error[0].Exception.Message -eq 'Exception setting "CursorVisible": "The handle is invalid."')
        {
            $Global:Error.Remove($Global:Error[0])
        }
```

Validating the issue now and then will submit a PR.

**Comment by gravypower** [comment] 2020-02-08 05:33
I have applied this change and I can confirm it fixes this issue for me.

**Comment by pbering** [comment] 2020-02-08 11:55
Fix is merged now, thanks for reporting!

**Closed by pbering** 2020-02-08 11:55 UTC
